Age = input("Whow old are you?")
Age2 = input("Whow old is your friend?")
Age3 = input("Whow old is your Mom?")
Age4 = input("Whow old is your Dad?")

print(int(Age4) < int(Age2))
print(int(Age) > int(Age2))
print(int(Age3) <= int(Age2))
print(int(Age2) >= int(Age2))
print(int(Age4) != int(Age))
print(int(Age) == int(Age))
print(int(Age4) < int(Age))
print(int(Age) > int(Age))
print(int(Age) <= int(Age3))
print(int(Age2) >= int(Age3))
print(int(Age3) != int(Age3))
print(int(Age4) == int(Age3))
print(int(Age) < int(Age3))
print(int(Age3) > int(Age4))
print(int(Age2) <= int(Age4))
print(int(Age) >= int(Age4))
print(int(Age4) == int(Age4))

